/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio6;

/**
 *
 * @author rubinoma
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcionEj1 = new javax.swing.JMenuItem();
        opcionEj2 = new javax.swing.JMenuItem();
        opcionEj3 = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Ejercicios");

        opcionEj1.setText("Ejercicio 1");
        opcionEj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEj1ActionPerformed(evt);
            }
        });
        jMenu1.add(opcionEj1);

        opcionEj2.setText("Ejercicio 2");
        opcionEj2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEj2ActionPerformed(evt);
            }
        });
        jMenu1.add(opcionEj2);

        opcionEj3.setText("Ejercicio 3");
        opcionEj3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionEj3ActionPerformed(evt);
            }
        });
        jMenu1.add(opcionEj3);
        jMenu1.add(separador);

        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        jMenu1.add(opcionSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionEj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEj1ActionPerformed
        VentanaEj1 vent = new VentanaEj1();
        vent.setVisible(true);
    }//GEN-LAST:event_opcionEj1ActionPerformed

    private void opcionEj2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEj2ActionPerformed
        VentanaEj2 vent = new VentanaEj2();
        vent.setVisible(true);
    }//GEN-LAST:event_opcionEj2ActionPerformed

    private void opcionEj3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionEj3ActionPerformed
        VentanaEj3 vent = new VentanaEj3();
        vent.setVisible(true);
    }//GEN-LAST:event_opcionEj3ActionPerformed

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        dispose();
    }//GEN-LAST:event_opcionSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcionEj1;
    private javax.swing.JMenuItem opcionEj2;
    private javax.swing.JMenuItem opcionEj3;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
