/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio6;

import ejercicio2.*;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Rubino
 */
public class VentanaEj2 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public VentanaEj2() {
        initComponents();
        this.setSize(400, 250);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        optAzul = new javax.swing.JRadioButton();
        optRojo = new javax.swing.JRadioButton();
        btnAutor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 250));
        getContentPane().setLayout(null);

        grupo.add(optAzul);
        optAzul.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optAzul.setText("Azul");
        optAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optAzulActionPerformed(evt);
            }
        });
        getContentPane().add(optAzul);
        optAzul.setBounds(130, 70, 110, 23);

        grupo.add(optRojo);
        optRojo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        optRojo.setText("Rojo");
        optRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optRojoActionPerformed(evt);
            }
        });
        getContentPane().add(optRojo);
        optRojo.setBounds(130, 30, 110, 23);

        btnAutor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAutor.setText("Autor");
        btnAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAutorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAutor);
        btnAutor.setBounds(140, 140, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAutorActionPerformed
        JOptionPane.showMessageDialog(this, "Curso de Programación 2 - Universidad ORT", "Autor", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAutorActionPerformed

    private void optRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optRojoActionPerformed
        btnAutor.setForeground(Color.red);
    }//GEN-LAST:event_optRojoActionPerformed

    private void optAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optAzulActionPerformed
        btnAutor.setForeground(Color.blue);
    }//GEN-LAST:event_optAzulActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAutor;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JRadioButton optAzul;
    private javax.swing.JRadioButton optRojo;
    // End of variables declaration//GEN-END:variables
}
