package ejercicio4;

import java.awt.Color;
import java.awt.event.*;
import javax.swing.Timer;

public class Semaforo extends javax.swing.JFrame {

    public Semaforo() {
        initComponents();
        this.setSize(400, 310);
        btnRojo.setBackground(Color.gray);
        btnAmarillo.setBackground(Color.gray);
        btnVerde.setBackground(Color.gray);
        luz = 0;
        miTimer = new Timer (2000, new ActionListener () { 
            public void actionPerformed(ActionEvent e) {
                luz++;
                if (luz==4)
                    luz = 1;
                switch(luz){
                    case 1:
                        btnVerde.setBackground(Color.gray);
                        btnRojo.setBackground(Color.red);
                        break;
                    case 2:
                        btnRojo.setBackground(Color.gray);
                        btnAmarillo.setBackground(Color.yellow);
                        break;
                    case 3:
                        btnAmarillo.setBackground(Color.gray);
                        btnVerde.setBackground(Color.green);
                        break;
                }
            } 
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerde = new javax.swing.JButton();
        btnRojo = new javax.swing.JButton();
        btnAmarillo = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(btnVerde);
        btnVerde.setBounds(100, 180, 70, 60);
        getContentPane().add(btnRojo);
        btnRojo.setBounds(100, 40, 70, 60);
        getContentPane().add(btnAmarillo);
        btnAmarillo.setBounds(100, 110, 70, 60);

        btnFin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFin.setText("Fin");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinActionPerformed(evt);
            }
        });
        getContentPane().add(btnFin);
        btnFin.setBounds(270, 150, 90, 30);

        btnInicio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnInicio);
        btnInicio.setBounds(270, 100, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        miTimer.start();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinActionPerformed
        miTimer.stop();
    }//GEN-LAST:event_btnFinActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRojo;
    private javax.swing.JButton btnVerde;
    // End of variables declaration//GEN-END:variables
    private Timer miTimer;
    private int luz;
}
