package ejercicio8;
public class VentanaMenu extends javax.swing.JFrame {

    public VentanaMenu(Sistema unSistema) {
        modelo = unSistema;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opcionIngreso = new javax.swing.JMenuItem();
        opcionConsulta = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        opcionSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opciones");

        opcionIngreso.setText("Ingresar Pelicula");
        opcionIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionIngresoActionPerformed(evt);
            }
        });
        jMenu1.add(opcionIngreso);

        opcionConsulta.setText("Consulta Peliculas");
        opcionConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionConsultaActionPerformed(evt);
            }
        });
        jMenu1.add(opcionConsulta);
        jMenu1.add(separador);

        opcionSalir.setText("Salir");
        opcionSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcionSalirActionPerformed(evt);
            }
        });
        jMenu1.add(opcionSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcionIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionIngresoActionPerformed
        VentanaIngreso vent = new VentanaIngreso(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionIngresoActionPerformed

    private void opcionConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionConsultaActionPerformed
        VentanaConsulta vent = new VentanaConsulta(modelo);
        vent.setVisible(true);
    }//GEN-LAST:event_opcionConsultaActionPerformed

    private void opcionSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcionSalirActionPerformed
        dispose();
    }//GEN-LAST:event_opcionSalirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opcionConsulta;
    private javax.swing.JMenuItem opcionIngreso;
    private javax.swing.JMenuItem opcionSalir;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
    private Sistema modelo;
}
